cmake_minimum_required(VERSION 3.20)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(tracker_finder_tests LANGUAGES CXX)
  enable_testing()
endif()
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(tracker_finder_test tracker_finder_test.cpp)
target_include_directories(tracker_finder_test PRIVATE ../../src/app/app_17)
if(MSVC)
  target_compile_options(tracker_finder_test PRIVATE /W4 /WX)
else()
  target_compile_options(tracker_finder_test PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME tracker_finder COMMAND tracker_finder_test)
set_tests_properties(tracker_finder PROPERTIES TIMEOUT 15)
